---
title: "500-single-chrom-PCAs"
author: "Mac Campbell"
date: "November 13, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
```

## Maybe some PCAs will highlight chroms of interest
I can use the test chroms first to see if it is interesting. That is chrom 28, NC_037124.1.     

```{sh, eval=FALSE}
python $HOME/pcangsd/pcangsd.py -beagle outputs/300/NC_037124.1-pca.beagle.gz -o outputs/300/NC_037124.1 -threads 10

python $HOME/pcangsd/pcangsd.py -beagle outputs/300/NC_037130.1-pca.beagle.gz -o outputs/300/NC_037130.1 -threads 10
```
```{sh, eval=FALSE}
scp -P 2022 farm:~/shernook/outputs/300/NC_037124.1.cov outputs/500/
scp -P 2022 farm:~/shernook/outputs/300/NC_037130.1.cov outputs/500/
```



```{r}
#' @param samples character vector with the individuals IDs in the order in which
#' they were passed in the bamlist to angsd.
#' @param cov covariance matrix
covar2pcs <- function(samples, cov) {
  
  
  eig <- eigen(cov, symm = TRUE)
  PC <- as.data.frame(eig$vectors) %>%
    as_tibble() %>%
    setNames(sprintf("PC-%02d", 1:ncol(.)))
  
  samtib <- tibble(sample = samples)
  
  list(
    PCs = bind_cols(samtib, PC),
    eigevalues = eig$values
  )
}

```

```{r}
cov<-read_delim("outputs/500/NC_037124.1.cov", col_names=FALSE, delim=" ") %>% as.matrix()

load("meta/tot.rda")

pca <- covar2pcs(tot$`Sample ID`, cov)

pca_long <- pca$PCs %>%
  tidyr::gather(., key = "PC", "val", -sample)

# then expand a grid of the possible comparisons (ordered)
expg <- expand.grid(sample = pca$PCs$sample,
                    PCx = sprintf("PC-%02d", 1:6),
                    PCy = sprintf("PC-%02d", 1:6),
                    stringsAsFactors = FALSE) %>%
  tibble::as_tibble()

# then left join the pca results onto that
pca_pairs <- dplyr::left_join(expg, pca_long, by = c("sample", "PCx" = "PC")) %>%
  dplyr::rename(val_x = val) %>%
  dplyr::left_join(pca_long, by = c("sample", "PCy" = "PC")) %>%
  dplyr::rename(val_y = val)

pp_meta <- pca_pairs %>%   # just keep the first 6 PCs around
  left_join(., tot, by = c("sample" = "Sample ID")) 

npc <- 3
pp_meta2 <- pp_meta %>%
  filter( (PCx %in% sprintf("PC-%02d", 1:npc)) & 
            (PCy %in% sprintf("PC-%02d", 1:npc)) )

eig <- eigen(cov, symm = TRUE)
var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)

```

```{r}
ggplot(pp_meta2) +
  geom_point(aes(x=val_x, y=val_y, shape=Run, color=Tributary)) +
  coord_fixed() +
  facet_grid (PCx ~ PCy) +
  theme_bw()
```

```{r}
ppsub <- pp_meta2 %>% filter(PCx == "PC-01") %>% filter(PCy=="PC-02")

ggplot(ppsub) +
  geom_point(aes(x=val_x, y=val_y, color=Run)) +
  coord_fixed() +
  theme_bw()
```

```{r}
feather<-pp_meta2 %>% filter(Tributary %in% c("Feather River Hatchery Fall","Feather River Hatchery Spring")) %>% 
  filter(PCx == "PC-01") %>% filter(PCy=="PC-02")

ggplot(feather) +
  geom_point(aes(x=val_x, y=val_y, color=Run)) +
  theme_bw()
ggave("outputs/500/feather-only.jpg")
```

```{r}
filtered<-pp_meta2 %>% filter(!(Tributary %in% c("Feather River Hatchery Fall","Feather River Hatchery Spring"))) %>% 
  filter(Run !="Winter") %>%
  filter(PCx == "PC-01") %>% filter(PCy=="PC-02")

ggplot(filtered) +
  geom_point(aes(x=val_x, y=val_y, color=Run)) +
  theme_bw()
ggsave("outputs/500/filtered.jpg")
```

```{r}
filtered2<-pp_meta2 %>% filter(Tributary %in% c("Butte", "Butte Creek Spring","Deer","Mill")) %>% 
  filter(Run !="Winter") %>%
  filter(PCx == "PC-01") %>% filter(PCy=="PC-02")

ggplot(filtered2) +
  geom_point(aes(x=val_x, y=val_y, color=Run)) +
  theme_bw()
ggsave("outputs/500/filtered2.jpg")
```
#Winter
```{r}
cov<-read_delim("outputs/500/NC_037130.1.cov", col_names=FALSE, delim=" ") %>% as.matrix()

load("meta/tot.rda")

pca <- covar2pcs(tot$`Sample ID`, cov)

pca_long <- pca$PCs %>%
  tidyr::gather(., key = "PC", "val", -sample)

# then expand a grid of the possible comparisons (ordered)
expg <- expand.grid(sample = pca$PCs$sample,
                    PCx = sprintf("PC-%02d", 1:6),
                    PCy = sprintf("PC-%02d", 1:6),
                    stringsAsFactors = FALSE) %>%
  tibble::as_tibble()

# then left join the pca results onto that
pca_pairs <- dplyr::left_join(expg, pca_long, by = c("sample", "PCx" = "PC")) %>%
  dplyr::rename(val_x = val) %>%
  dplyr::left_join(pca_long, by = c("sample", "PCy" = "PC")) %>%
  dplyr::rename(val_y = val)

pp_meta <- pca_pairs %>%   # just keep the first 6 PCs around
  left_join(., tot, by = c("sample" = "Sample ID")) 

npc <- 3
pp_meta2 <- pp_meta %>%
  filter( (PCx %in% sprintf("PC-%02d", 1:npc)) & 
            (PCy %in% sprintf("PC-%02d", 1:npc)) )

eig <- eigen(cov, symm = TRUE)
var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)

ppsub <- pp_meta2 %>% filter(PCx == "PC-01") %>% filter(PCy=="PC-02")

ggplot(ppsub) +
  geom_point(aes(x=val_x, y=val_y, color=Run)) +
  coord_fixed() +
  theme_bw()
```
